Models/ErrorViewModel.cs
namespace MZ_PROGRESO1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ZUMARRAGA.cs
using System.ComponentModel.DataAnnotations;

namespace MZ_PROGRESO1.Models
{
    public class ZUMARRAGA
    {
        [Required(ErrorMessage = "Escriba el codigo.")]
        //[RegularExpression("^[0-9]{9}-[0-9]{1}$", ErrorMessage = "Escriba un codigo valido.")]
        [Key]
        public int mzCodigo { get; set; }

        [Required(ErrorMessage = "Escriba la calificacion final.")]
        [Range(0.01, 10.0)]
        public decimal mzCalificacionFinal { get; set; }

        [Required(ErrorMessage = "Escriba el nombre y apellido.")]
        [MinLength(5, ErrorMessage = "Escriba al menos 5 caractéres.")]
        [MaxLength(50, ErrorMessage = "Escriba un máximo de 5 caractéres.")]
        public string? mzNombre { get; set; }

        [Required(ErrorMessage = "Escriba el nombre y apellido.")]
        [MinLength(5, ErrorMessage = "Escriba al menos 5 caractéres.")]
        [MaxLength(50, ErrorMessage = "Escriba un máximo de 5 caractéres.")]
        public string? mzApellido { get; set; }

        [Required(ErrorMessage = "Escriba el correo.")]
        [EmailAddress(ErrorMessage = "Escriba un correo válido.")]
        public string? mzCorreo { get; set; }

        [Required(ErrorMessage = "Escriba el codigo postal.")]
        public string? mzCodigoPostal { get; set; }

        public bool mzEstudianteNuevo { get; set; }

        [Required(ErrorMessage = "Escriba la fecha de nacimiento.")]
        public DateTime mzFechaNacimiento { get; set; }

        [Required(ErrorMessage = "Escriba la calificacion final.")]
        [Range(0.01, 5.0)]
        public float mzPromedioConducta { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MZ_PROGRESO1.Models;

namespace MZ_PROGRESO1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ZUMARRAGAsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MZ_PROGRESO1.Data;
using MZ_PROGRESO1.Models;

namespace MZ_PROGRESO1.Controllers
{
    public class ZUMARRAGAsController : Controller
    {
        private readonly MZ_PROGRESO1Context _context;

        public ZUMARRAGAsController(MZ_PROGRESO1Context context)
        {
            _context = context;
        }

        // GET: ZUMARRAGAs
        public async Task<IActionResult> Index()
        {
              return _context.ZUMARRAGA != null ? 
                          View(await _context.ZUMARRAGA.ToListAsync()) :
                          Problem("Entity set 'MZ_PROGRESO1Context.ZUMARRAGA'  is null.");
        }

        // GET: ZUMARRAGAs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ZUMARRAGA == null)
            {
                return NotFound();
            }

            var zUMARRAGA = await _context.ZUMARRAGA
                .FirstOrDefaultAsync(m => m.mzCodigo == id);
            if (zUMARRAGA == null)
            {
                return NotFound();
            }

            return View(zUMARRAGA);
        }

        // GET: ZUMARRAGAs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ZUMARRAGAs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("mzCodigo,mzCalificacionFinal,mzNombre,mzApellido,mzCorreo,mzCodigoPostal,mzEstudianteNuevo,mzFechaNacimiento,mzPromedioConducta")] ZUMARRAGA zUMARRAGA)
        {
            if (ModelState.IsValid)
            {
                _context.Add(zUMARRAGA);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(zUMARRAGA);
        }

        // GET: ZUMARRAGAs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ZUMARRAGA == null)
            {
                return NotFound();
            }

            var zUMARRAGA = await _context.ZUMARRAGA.FindAsync(id);
            if (zUMARRAGA == null)
            {
                return NotFound();
            }
            return View(zUMARRAGA);
        }

        // POST: ZUMARRAGAs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("mzCodigo,mzCalificacionFinal,mzNombre,mzApellido,mzCorreo,mzCodigoPostal,mzEstudianteNuevo,mzFechaNacimiento,mzPromedioConducta")] ZUMARRAGA zUMARRAGA)
        {
            if (id != zUMARRAGA.mzCodigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(zUMARRAGA);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ZUMARRAGAExists(zUMARRAGA.mzCodigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(zUMARRAGA);
        }

        // GET: ZUMARRAGAs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ZUMARRAGA == null)
            {
                return NotFound();
            }

            var zUMARRAGA = await _context.ZUMARRAGA
                .FirstOrDefaultAsync(m => m.mzCodigo == id);
            if (zUMARRAGA == null)
            {
                return NotFound();
            }

            return View(zUMARRAGA);
        }

        // POST: ZUMARRAGAs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ZUMARRAGA == null)
            {
                return Problem("Entity set 'MZ_PROGRESO1Context.ZUMARRAGA'  is null.");
            }
            var zUMARRAGA = await _context.ZUMARRAGA.FindAsync(id);
            if (zUMARRAGA != null)
            {
                _context.ZUMARRAGA.Remove(zUMARRAGA);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ZUMARRAGAExists(int id)
        {
          return (_context.ZUMARRAGA?.Any(e => e.mzCodigo == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MZ_EVALUACION_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MZ_PROGRESO1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MZ_PROGRESO1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">MENU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ZUMARRAGAs" asp-action="Index">TABLA_MZ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MZ_PROGRESO1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/ZUMARRAGAs/Create.cshtml
@model MZ_PROGRESO1.Models.ZUMARRAGA

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ZUMARRAGA</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="mzCalificacionFinal" class="control-label"></label>
                <input asp-for="mzCalificacionFinal" class="form-control" />
                <span asp-validation-for="mzCalificacionFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzNombre" class="control-label"></label>
                <input asp-for="mzNombre" class="form-control" />
                <span asp-validation-for="mzNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzApellido" class="control-label"></label>
                <input asp-for="mzApellido" class="form-control" />
                <span asp-validation-for="mzApellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzCorreo" class="control-label"></label>
                <input asp-for="mzCorreo" class="form-control" />
                <span asp-validation-for="mzCorreo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzCodigoPostal" class="control-label"></label>
                <input asp-for="mzCodigoPostal" class="form-control" />
                <span asp-validation-for="mzCodigoPostal" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="mzEstudianteNuevo" /> @Html.DisplayNameFor(model => model.mzEstudianteNuevo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="mzFechaNacimiento" class="control-label"></label>
                <input asp-for="mzFechaNacimiento" class="form-control" />
                <span asp-validation-for="mzFechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzPromedioConducta" class="control-label"></label>
                <input asp-for="mzPromedioConducta" class="form-control" />
                <span asp-validation-for="mzPromedioConducta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ZUMARRAGAs/Delete.cshtml
@model MZ_PROGRESO1.Models.ZUMARRAGA

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ZUMARRAGA</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzCalificacionFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzCalificacionFinal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzApellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzApellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzCorreo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzCorreo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzCodigoPostal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzCodigoPostal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzEstudianteNuevo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzEstudianteNuevo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzFechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzFechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzPromedioConducta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzPromedioConducta)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="mzCodigo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ZUMARRAGAs/Details.cshtml
@model MZ_PROGRESO1.Models.ZUMARRAGA

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ZUMARRAGA</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzCalificacionFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzCalificacionFinal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzApellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzApellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzCorreo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzCorreo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzCodigoPostal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzCodigoPostal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzEstudianteNuevo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzEstudianteNuevo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzFechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzFechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mzPromedioConducta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mzPromedioConducta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.mzCodigo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ZUMARRAGAs/Edit.cshtml
@model MZ_PROGRESO1.Models.ZUMARRAGA

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ZUMARRAGA</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="mzCodigo" />
            <div class="form-group">
                <label asp-for="mzCalificacionFinal" class="control-label"></label>
                <input asp-for="mzCalificacionFinal" class="form-control" />
                <span asp-validation-for="mzCalificacionFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzNombre" class="control-label"></label>
                <input asp-for="mzNombre" class="form-control" />
                <span asp-validation-for="mzNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzApellido" class="control-label"></label>
                <input asp-for="mzApellido" class="form-control" />
                <span asp-validation-for="mzApellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzCorreo" class="control-label"></label>
                <input asp-for="mzCorreo" class="form-control" />
                <span asp-validation-for="mzCorreo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzCodigoPostal" class="control-label"></label>
                <input asp-for="mzCodigoPostal" class="form-control" />
                <span asp-validation-for="mzCodigoPostal" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="mzEstudianteNuevo" /> @Html.DisplayNameFor(model => model.mzEstudianteNuevo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="mzFechaNacimiento" class="control-label"></label>
                <input asp-for="mzFechaNacimiento" class="form-control" />
                <span asp-validation-for="mzFechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mzPromedioConducta" class="control-label"></label>
                <input asp-for="mzPromedioConducta" class="form-control" />
                <span asp-validation-for="mzPromedioConducta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ZUMARRAGAs/Index.cshtml
@model IEnumerable<MZ_PROGRESO1.Models.ZUMARRAGA>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.mzCalificacionFinal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzApellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzCorreo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzCodigoPostal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzEstudianteNuevo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzFechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mzPromedioConducta)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.mzCalificacionFinal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzCorreo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzCodigoPostal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzEstudianteNuevo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzFechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mzPromedioConducta)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.mzCodigo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.mzCodigo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.mzCodigo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>